apiVersion: 1

datasources:
  - name: Redis
    type: redis-datasource
    access: proxy
    isDefault: true
    orgId: 1
    version: 1
    url: redis://cache:6379
    secureJsonData:
      password: $REDIS_PASSWORD
    jsonData:
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    editable: true
